import { NextResponse } from 'next/server';
import sql from '@/api-old/db/connection';
import nodemailer from 'nodemailer';
import { normalizeRows } from '@/lib/db-utils';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    const {
      client_name,
      client_email,
      client_phone,
      client_company,
      event_type,
      event_date,
      event_location,
      guest_count,
      services_requested,
      budget_range,
      message,
      referral_source
    } = body;
    
    // Validation
    if (!client_name || !client_email) {
      return NextResponse.json({
        success: false,
        error: 'Name and email are required'
      }, { status: 400 });
    }
    
    // Insert inquiry into database (inquiry_number will be auto-generated by trigger)
    const insertResult = await sql`
      INSERT INTO client_inquiries (
        inquiry_number,
        client_name,
        client_email,
        client_phone,
        client_company,
        event_type,
        event_date,
        event_location,
        guest_count,
        services_requested,
        budget_range,
        message,
        referral_source,
        status
      ) VALUES (
        '',
        ${client_name},
        ${client_email},
        ${client_phone || null},
        ${client_company || null},
        ${event_type || null},
        ${event_date || null},
        ${event_location || null},
        ${guest_count || null},
        ${services_requested || []},
        ${budget_range || null},
        ${message || null},
        ${referral_source || null},
        'new'
      )
      RETURNING *
    `;
    const result = normalizeRows(insertResult);
    
    const inquiry = result[0];
    
    // Send email notification to admin
    try {
      await sendInquiryNotification(inquiry);
    } catch (emailError) {
      console.error('Failed to send inquiry notification:', emailError);
      // Don't fail the request if email fails
    }
    
    // Send confirmation email to client
    try {
      await sendClientConfirmation(inquiry);
    } catch (emailError) {
      console.error('Failed to send client confirmation:', emailError);
    }
    
    return NextResponse.json({
      success: true,
      inquiry_number: inquiry.inquiry_number,
      message: 'Inquiry submitted successfully'
    });
    
  } catch (error: any) {
    console.error('Inquiry submission error:', error);
    return NextResponse.json({
      success: false,
      error: error.message || 'Failed to submit inquiry'
    }, { status: 500 });
  }
}

// Send email notification to admin
async function sendInquiryNotification(inquiry: any) {
  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_APP_PASSWORD;
  const adminEmail = process.env.ADMIN_NOTIFICATION_EMAIL || 'lee@externallyyoursproductions.com';
  const crmUrl = process.env.CRM_ADMIN_URL || 'https://eyp-static.vercel.app/crm-admin';
  
  if (!gmailUser || !gmailPass) {
    console.log('Gmail not configured, skipping notification email');
    return;
  }
  
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: gmailUser,
      pass: gmailPass
    }
  });
  
  const servicesText = Array.isArray(inquiry.services_requested) && inquiry.services_requested.length > 0
    ? inquiry.services_requested.join(', ')
    : 'Not specified';
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #ff6b35 0%, #f41b1b 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 28px;">🎉 New Client Inquiry!</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">Inquiry #${inquiry.inquiry_number}</p>
      </div>
      
      <div style="background: white; padding: 30px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 10px 10px;">
        <h2 style="color: #1a1a1a; margin-top: 0;">Client Information</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666; width: 40%;">Name:</td>
            <td style="padding: 10px 0;">${inquiry.client_name}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Email:</td>
            <td style="padding: 10px 0;"><a href="mailto:${inquiry.client_email}" style="color: #ff6b35;">${inquiry.client_email}</a></td>
          </tr>
          ${inquiry.client_phone ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Phone:</td>
            <td style="padding: 10px 0;">${inquiry.client_phone}</td>
          </tr>
          ` : ''}
          ${inquiry.client_company ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Company:</td>
            <td style="padding: 10px 0;">${inquiry.client_company}</td>
          </tr>
          ` : ''}
        </table>
        
        <h2 style="color: #1a1a1a;">Event Details</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          ${inquiry.event_type ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666; width: 40%;">Event Type:</td>
            <td style="padding: 10px 0;">${inquiry.event_type}</td>
          </tr>
          ` : ''}
          ${inquiry.event_date ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Event Date:</td>
            <td style="padding: 10px 0;">${new Date(inquiry.event_date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</td>
          </tr>
          ` : ''}
          ${inquiry.event_location ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Location:</td>
            <td style="padding: 10px 0;">${inquiry.event_location}</td>
          </tr>
          ` : ''}
          ${inquiry.guest_count ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Guest Count:</td>
            <td style="padding: 10px 0;">${inquiry.guest_count}</td>
          </tr>
          ` : ''}
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Services:</td>
            <td style="padding: 10px 0;">${servicesText}</td>
          </tr>
          ${inquiry.budget_range ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Budget Range:</td>
            <td style="padding: 10px 0;">${inquiry.budget_range}</td>
          </tr>
          ` : ''}
          ${inquiry.referral_source ? `
          <tr>
            <td style="padding: 10px 0; font-weight: 600; color: #666;">Referral Source:</td>
            <td style="padding: 10px 0;">${inquiry.referral_source}</td>
          </tr>
          ` : ''}
        </table>
        
        ${inquiry.message ? `
        <h2 style="color: #1a1a1a;">Message</h2>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 4px solid #ff6b35; margin-bottom: 20px;">
          <p style="margin: 0; white-space: pre-wrap;">${inquiry.message}</p>
        </div>
        ` : ''}
        
        <div style="text-align: center; margin-top: 30px;">
          <a href="${crmUrl}/inquiries" style="display: inline-block; background: #ff6b35; color: white; padding: 15px 40px; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 16px;">View in CRM Dashboard</a>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #999; font-size: 12px;">
          <p>This is an automated notification from your CRM system</p>
        </div>
      </div>
    </body>
    </html>
  `;
  
  await transporter.sendMail({
    from: `"Externally Yours Productions CRM" <${gmailUser}>`,
    to: adminEmail,
    subject: `New Inquiry - ${inquiry.client_name} - ${inquiry.event_type || 'Event'}`,
    html: htmlContent
  });
}

// Send confirmation email to client
async function sendClientConfirmation(inquiry: any) {
  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_APP_PASSWORD;
  
  if (!gmailUser || !gmailPass) {
    return;
  }
  
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: gmailUser,
      pass: gmailPass
    }
  });
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 28px;">Thank You, ${inquiry.client_name}!</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">We've received your inquiry</p>
      </div>
      
      <div style="background: white; padding: 30px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 10px 10px;">
        <p style="font-size: 16px; color: #333; margin-top: 0;">
          Thank you for your interest in Externally Yours Productions! We're excited to learn more about your upcoming event.
        </p>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #ff6b35; margin: 20px 0;">
          <p style="margin: 0 0 10px 0; font-weight: 600; color: #1a1a1a;">Inquiry Reference Number:</p>
          <p style="margin: 0; font-size: 18px; color: #ff6b35; font-weight: bold;">${inquiry.inquiry_number}</p>
        </div>
        
        <h3 style="color: #1a1a1a; margin-top: 25px;">What happens next?</h3>
        <ul style="list-style: none; padding: 0;">
          <li style="padding: 10px 0; display: flex; align-items: flex-start;">
            <span style="color: #ff6b35; font-size: 20px; margin-right: 10px;">1️⃣</span>
            <span>Our team will review your inquiry within 24 hours</span>
          </li>
          <li style="padding: 10px 0; display: flex; align-items: flex-start;">
            <span style="color: #ff6b35; font-size: 20px; margin-right: 10px;">2️⃣</span>
            <span>We'll reach out to schedule a consultation to discuss your vision</span>
          </li>
          <li style="padding: 10px 0; display: flex; align-items: flex-start;">
            <span style="color: #ff6b35; font-size: 20px; margin-right: 10px;">3️⃣</span>
            <span>We'll create a custom proposal tailored to your event</span>
          </li>
        </ul>
        
        <div style="background: #fff8f5; padding: 20px; border-radius: 8px; margin: 25px 0;">
          <p style="margin: 0; color: #666; font-size: 14px;">
            <strong>Questions?</strong> Reply to this email or call us at <a href="tel:+1234567890" style="color: #ff6b35; text-decoration: none;">123-456-7890</a>
          </p>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #999; font-size: 12px;">
          <p>Externally Yours Productions<br/>
          Making your events extraordinary</p>
        </div>
      </div>
    </body>
    </html>
  `;
  
  await transporter.sendMail({
    from: `"Externally Yours Productions" <${gmailUser}>`,
    to: inquiry.client_email,
    subject: `We've Received Your Inquiry - ${inquiry.inquiry_number}`,
    html: htmlContent
  });
}

export async function GET() {
  return NextResponse.json({
    message: 'Use POST to submit an inquiry'
  });
}
